pring.datasource.url=jdbc:mysql://localhost:3306/carhelper_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Aa@12345678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
ai.api.key=AIzaSyBw7g6w1I3mlxif0ndg0fs72zoISfLsR_I